### ISSUE TITLE
PHP 8 Union Types Issue

### ISSUE THREAD

**Issue by liamkeily** [ohmysmtp/ohmysmtp-swiftmailer#1]
I am getting the following error:

`syntax error, unexpected '|', expecting variable (T_VARIABLE)`

This is because Union Types (PHP 8 Feature) is being used here https://github.com/ohmysmtp/ohmysmtp-swiftmailer/blob/main/src/OhmysmtpSwiftmailerTransport.php#L105

The composer.json file for this package shows support for `>= PHP 7.3 ` https://github.com/ohmysmtp/ohmysmtp-swiftmailer/blob/main/composer.json#L22 (I am using PHP 7.4)

**Comment by paul-oms** [comment]
@liamkeily thanks for raising
